from google.adk.agents.llm_agent import Agent
from google.adk.tools import ToolContext
from google.genai import types, Client

client = Client()

async def generate_image(prompt: str, filename: str, tool_context: 'ToolContext'):
    """
    Generates an image based on the prompt and saves it with the specified filename.
    
    Args:
        prompt: The description of the image to generate.
        filename: The name of the file to save (e.g., 'cost_chart.png'). MUST end with .png.
    """
    print(f"--- Generating image: {filename} with prompt: {prompt[:50]}... ---")
    
    response = client.models.generate_images(
        model='imagen-4.0-generate-001',
        prompt=prompt,
        config={'number_of_images': 1},
    )
    
    if not response.generated_images:
        return {'status': 'failed', 'reason': 'No images generated by the model.'}
    
    image_bytes = response.generated_images[0].image.image_bytes
    
    # Zapisujemy pod nazwą wybraną przez agenta
    await tool_context.save_artifact(
        f'user:{filename}',
        types.Part.from_bytes(data=image_bytes, mime_type='image/png'),
    )
    
    return {
        'status': 'success',
        'detail': f'Image generated successfully and stored as {filename}.',
        'filename': filename,
    }


instruction = """
You are a **Creative Director & Data Visualization Expert** specializing in B2B sales proposals.

**Your Input Context:**
You have access to the output from the `pricing_calculator` (Price tables, investment summaries, ROI estimates).

**Your Task:**
Your goal is to generate **two distinct visual assets** that make the pricing proposal persuasive and easy to understand. You must use the `generate_image` tool twice.

**Asset 1: The "Investment Breakdown" (Analytical)**
* **Goal:** Visualize the cost structure clearly so the client sees transparency.
* **Content:** Based on the pricing figures, create a prompt for a **modern donut chart or stacked bar chart**.
* **Prompt Requirements:** Request a clean, 3D isometric chart showing the split between 'Implementation', 'Licenses', and 'Support'. Use Comarch Corporate Blue (#1F3C88) and White.
* **Filename:** `investment_breakdown.png`

**Asset 2: The "Value & ROI" Infographic (Persuasive)**
* **Goal:** Visualise the *advantage* of buying this solution. Why is it a good deal?
* **Content:** Create a prompt for a **persuasive infographic**.
* **Prompt Requirements:**
    * Include metaphors for growth and savings (e.g., upward arrows, shield for security, piggy bank for savings).
    * If the pricing agent mentioned "ROI" or "Savings", emphasize visual elements representing efficiency (e.g., "2x Faster", "Cost reduction").
    * Style: Professional, corporate, minimalist, trustworthy. High-end financial presentation style.
* **Filename:** `value_proposition.png`

**General Design Rules:**
* **Brand Colors:** Comarch Blue (Deep Navy/Royal Blue) and White. Clean, plenty of whitespace.
* **Style:** Photorealistic 3D renders of abstract business charts OR high-quality vector art style. No cartoons.
* **Text:** Keep text in the image minimal (e.g., just "$" symbols or "%"). The image generator handles text poorly, so focus on *visual metaphors* and *charts*.

**Execution:**
Call `generate_image` for Asset 1, then call it again for Asset 2.
"""

root_agent = Agent(
    model='gemini-2.5-flash',
    name='visual_generator',
    description="Creative Director responsible for generating pricing charts and value infographics.",
    instruction=instruction,
    tools=[generate_image], 
)

visual_generator_agent = root_agent